# This should be the final docker file that creates the backend service
# This file should be run in the root directory of the backend
# This file should be run after all the Dockerfiles have been created

#Execution Command: docker-compose up

version: '3.7'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
  
  app3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
networks:
  private_net:
    driver: bridge
    