services:
  krakend:
    container_name: krakend
    build:
      context: ./kraken
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - private-network
      - public-network

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - private-network

  workout:
    container_name: workout
    depends_on:
      - postgres
    build: 
      context: ./workout
      dockerfile: Dockerfile
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
    internal: true
  public-network:
    driver: bridge