services:
  krakend:
    build:
      context: ./kraken
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - private-network
      - public-network

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks:
      - private-network

  workout:
    build: 
      context: ./workout
      dockerfile: Dockerfile
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
  public-network:
    driver: bridge