FROM postgres:latest

ENV POSTGRES_PASSWORD password

ENV POSTGRES_DB gitfitbro

ENV POSTGRES_USER postgres


COPY gitfitbroCurrent.sql /docker-entrypoint-initdb.d/gitfitbro.sql
COPY gitfitbroCurrent.sql /tmp/gitfitbro.sql

EXPOSE 5432

CMD [ "postgres" ]